%% ========================================================================
%  DIRECT EXCHANGE-AREA COMPUTATION
%
%  The direct exchange areas are computed from the DOM by successively
%  considering the emission of each radiative element. The resulting
%  exchange matrix is stored for subsequent use by the reduced model.
% ========================================================================

%% Radiative properties

radPropsBase = build_radiation_properties( ...
    geom, ...
    mesh, ...
    radFields, ...
    Twall_zone_table, ...
    matProps.fluid.kappa, ...
    physicalConst, ...
    radBcType2Tags, ...
    radBcType3Tags);


%% Direct exchange areas

[S, infoS] = compute_direct_exchange_areas( ...
    radSurf, ...
    geom, ...
    mesh, ...
    radPropsBase, ...
    radCtx, ...
    D, ...
    ang, ...
    physicalConst, ...
    struct('verbose', false));

%% Reduced radiation options

exchOpts = struct( ...
    'qImposedType3', q_imposed, ...
    'qImposedType2', 0);