%% ========================================================================
%  FULL REDUCED-MODEL COUPLING
%
%  The coupled solution iterates between the reduced radiation model,
%  wall and slab conduction, and the gas-zone energy balance. Gas
%  temperatures are redistributed to the radiative cells after each
%  energy-balance solution. Convergence is monitored on the slab, wall,
%  and gas-zone temperatures.
% ========================================================================

for outerIter = 1:maxOuterIter

    %% Radiation properties

    radProps = build_radiation_properties( ...
        geom, ...
        mesh, ...
        radFields, ...
        Twall_zone_table, ...
        matProps.fluid.kappa, ...
        physicalConst, ...
        radBcType2Tags, ...
        radBcType3Tags);


    %% Reduced radiation solution

    [radFields, exchInfo] = solve_radiation_exchange( ...
        S, ...
        radSurf, ...
        geom, ...
        mesh, ...
        radProps, ...
        physicalConst, ...
        radFields, ...
        exchOpts);


    %% Wall conduction

    if solveWalls

        wallOpts.wallState = wallState;

        [Twall_zone_table, wallState, infoWall] = ...
            solve_walls_conduction( ...
                wallCtx, ...
                radFields, ...
                geom, ...
                Twall_zone_table, ...
                physicalConst, ...
                wallOpts);

    end


    %% Slab conduction

    [radFields, slabCtxs, infoCond] = ...
        solve_slabs_conduction( ...
            slabCtxs, ...
            radFields, ...
            matProps, ...
            "steady", ...
            [], ...
            solverParams);


    %% Gas-zone energy balance

    [T_sub, zInfo] = solve_zones_energy( ...
        zEnCtx, ...
        gasProps, ...
        exchInfo, ...
        T_ez, ...
        src, ...
        physicalConst, ...
        zoneEnergyOpts);

    T_ez = zInfo.T_ez;


    %% Gas-temperature redistribution

    for p = 1:zEnCtx.nSub

        ge = zEnCtx.gasElemOfSub(p);

        radFields.T( ...
            double(radSurf.elem(ge).cells)) = T_sub(p);

    end


    %% Coupled convergence

    T_new_slab = radFields.T(slabCells);

    dT = norm(T_new_slab - T_prev_slab) / ...
         max(norm(T_new_slab), eps);


    if solveWalls

        Tsi_new = infoWall.Tsi;

        if isempty(Tsi_prev)

            dTwall = inf;

        else

            dTwall = norm(Tsi_new - Tsi_prev) / ...
                     max(norm(Tsi_new), eps);

        end

    else

        Tsi_new = [];
        dTwall  = 0;

    end


    dTzone = norm(T_ez - Tzone_prev) / ...
             max(norm(T_ez), eps);


    if dT < outerTol && ...
       dTwall < outerTol && ...
       dTzone < outerTol && ...
       outerIter > 1

        break

    end


    T_prev_slab = T_new_slab;
    Tsi_prev    = Tsi_new;
    Tzone_prev  = T_ez;

end